# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='meta',
            new_name='meta_url',
        ),
    ]
