# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
