# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20160815_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('type', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='share',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shares.MetaURL'),
        ),
    ]
