# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_auto_20160816_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaurl',
            name='image',
        ),
        migrations.RemoveField(
            model_name='metaurl',
            name='site_name',
        ),
    ]
