# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_auto_20160816_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaurl',
            name='og_object_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
