# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_metaurl_og_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaurl',
            name='og_object_id',
        ),
    ]
