# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 01:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook_url', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('icon_emoji', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SlashCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('team_domain', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('response_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField()),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=1)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_meta', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='slashcommand',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slack.WebhookTransaction'),
        ),
        migrations.AddField(
            model_name='incomingwebhook',
            name='webhook_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slack.WebhookTransaction'),
        ),
    ]
