# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingwebhook',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='incomingwebhook',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='incomingwebhook',
            name='repeat',
        ),
    ]
